LR_SPN = 0.001
LR_GAE = 0.0005
BATCH_SIZE = 4

# PRE_TRAIN_EPOCH=20
# SKELPOINT_TRAIN_EPOCH = 30
# GAE_TRAIN_EPOCH = 30

PRE_TRAIN_EPOCH=2
SKELPOINT_TRAIN_EPOCH = 3
GAE_TRAIN_EPOCH = 3

# JOINT_TRAIN_EPOCH = 30
# LR_DROP_CHECKPOINT = 90

# STEPS PER EPOCH = Total Training Examples / Batch Size * Number of Epochs
# STEPS PER EPOCH = 2000 / 4 * 20 = 10,000?